# Generated by Django 4.0.5 on 2022-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_zipcode', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('screenshot', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Reschedule', 'Reschedule'), ('Cancel', 'Cancel')], max_length=100)),
            ],
        ),
    ]
